// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (user_id, transaction_id, filename, original_name, mime_type, size, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, transaction_id, filename, original_name, mime_type, size, url, created_at
`

type CreateAttachmentParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	Filename      string      `json:"filename"`
	OriginalName  string      `json:"original_name"`
	MimeType      string      `json:"mime_type"`
	Size          int64       `json:"size"`
	Url           string      `json:"url"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.UserID,
		arg.TransactionID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.Size,
		arg.Url,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, user_id, transaction_id, filename, original_name, mime_type, size, url, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentsByTransactionID = `-- name: GetAttachmentsByTransactionID :many
SELECT id, user_id, transaction_id, filename, original_name, mime_type, size, url, created_at FROM attachments WHERE transaction_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAttachmentsByTransactionID(ctx context.Context, transactionID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
