// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: budgets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, amount, spent, month, year)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, category_id, amount, spent, month, year, created_at, updated_at
`

type CreateBudgetParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Amount     float64     `json:"amount"`
	Spent      float64     `json:"spent"`
	Month      int32       `json:"month"`
	Year       int32       `json:"year"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Spent,
		arg.Month,
		arg.Year,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Spent,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, category_id, amount, spent, month, year, created_at, updated_at FROM budgets WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id pgtype.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Spent,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetsByMonthYear = `-- name: GetBudgetsByMonthYear :many
SELECT id, user_id, category_id, amount, spent, month, year, created_at, updated_at FROM budgets WHERE user_id = $1 AND month = $2 AND year = $3 ORDER BY created_at DESC
`

type GetBudgetsByMonthYearParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  int32       `json:"month"`
	Year   int32       `json:"year"`
}

func (q *Queries) GetBudgetsByMonthYear(ctx context.Context, arg GetBudgetsByMonthYearParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getBudgetsByMonthYear, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Spent,
			&i.Month,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBudgetsByUserID = `-- name: GetBudgetsByUserID :many
SELECT id, user_id, category_id, amount, spent, month, year, created_at, updated_at FROM budgets WHERE user_id = $1 ORDER BY year DESC, month DESC
`

func (q *Queries) GetBudgetsByUserID(ctx context.Context, userID pgtype.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getBudgetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Spent,
			&i.Month,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET amount = $2,
    spent = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, category_id, amount, spent, month, year, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID     pgtype.UUID `json:"id"`
	Amount float64     `json:"amount"`
	Spent  float64     `json:"spent"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget, arg.ID, arg.Amount, arg.Spent)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Spent,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
