// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: debts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (user_id, name, total_amount, remaining_amount, interest_rate, due_date, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, total_amount, remaining_amount, interest_rate, due_date, status, notes, created_at, updated_at
`

type CreateDebtParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Name            string      `json:"name"`
	TotalAmount     float64     `json:"total_amount"`
	RemainingAmount float64     `json:"remaining_amount"`
	InterestRate    float64     `json:"interest_rate"`
	DueDate         pgtype.Date `json:"due_date"`
	Status          string      `json:"status"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.UserID,
		arg.Name,
		arg.TotalAmount,
		arg.RemainingAmount,
		arg.InterestRate,
		arg.DueDate,
		arg.Status,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDebtPayment = `-- name: CreateDebtPayment :one
INSERT INTO debt_payments (debt_id, amount, payment_date, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, debt_id, amount, payment_date, notes, created_at
`

type CreateDebtPaymentParams struct {
	DebtID      pgtype.UUID `json:"debt_id"`
	Amount      float64     `json:"amount"`
	PaymentDate pgtype.Date `json:"payment_date"`
	Notes       pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDebtPayment(ctx context.Context, arg CreateDebtPaymentParams) (DebtPayment, error) {
	row := q.db.QueryRow(ctx, createDebtPayment,
		arg.DebtID,
		arg.Amount,
		arg.PaymentDate,
		arg.Notes,
	)
	var i DebtPayment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Amount,
		&i.PaymentDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDebt = `-- name: DeleteDebt :exec
DELETE FROM debts WHERE id = $1
`

func (q *Queries) DeleteDebt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDebt, id)
	return err
}

const deleteDebtPayment = `-- name: DeleteDebtPayment :exec
DELETE FROM debt_payments WHERE id = $1
`

func (q *Queries) DeleteDebtPayment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDebtPayment, id)
	return err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, user_id, name, total_amount, remaining_amount, interest_rate, due_date, status, notes, created_at, updated_at FROM debts WHERE id = $1
`

func (q *Queries) GetDebtByID(ctx context.Context, id pgtype.UUID) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebtPaymentsByDebtID = `-- name: GetDebtPaymentsByDebtID :many
SELECT id, debt_id, amount, payment_date, notes, created_at FROM debt_payments WHERE debt_id = $1 ORDER BY payment_date DESC
`

func (q *Queries) GetDebtPaymentsByDebtID(ctx context.Context, debtID pgtype.UUID) ([]DebtPayment, error) {
	rows, err := q.db.Query(ctx, getDebtPaymentsByDebtID, debtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebtPayment{}
	for rows.Next() {
		var i DebtPayment
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Amount,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebtsByUserID = `-- name: GetDebtsByUserID :many
SELECT id, user_id, name, total_amount, remaining_amount, interest_rate, due_date, status, notes, created_at, updated_at FROM debts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDebtsByUserID(ctx context.Context, userID pgtype.UUID) ([]Debt, error) {
	rows, err := q.db.Query(ctx, getDebtsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TotalAmount,
			&i.RemainingAmount,
			&i.InterestRate,
			&i.DueDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :one
UPDATE debts
SET name = $2,
    total_amount = $3,
    remaining_amount = $4,
    interest_rate = $5,
    due_date = $6,
    status = $7,
    notes = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, total_amount, remaining_amount, interest_rate, due_date, status, notes, created_at, updated_at
`

type UpdateDebtParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	TotalAmount     float64     `json:"total_amount"`
	RemainingAmount float64     `json:"remaining_amount"`
	InterestRate    float64     `json:"interest_rate"`
	DueDate         pgtype.Date `json:"due_date"`
	Status          string      `json:"status"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebt,
		arg.ID,
		arg.Name,
		arg.TotalAmount,
		arg.RemainingAmount,
		arg.InterestRate,
		arg.DueDate,
		arg.Status,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
