// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: goals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, name, target_amount, current_amount, target_date, icon, color)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, target_amount, current_amount, target_date, icon, color, created_at, updated_at
`

type CreateGoalParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Name          string      `json:"name"`
	TargetAmount  float64     `json:"target_amount"`
	CurrentAmount float64     `json:"current_amount"`
	TargetDate    pgtype.Date `json:"target_date"`
	Icon          string      `json:"icon"`
	Color         string      `json:"color"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.TargetDate,
		arg.Icon,
		arg.Color,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.TargetDate,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoal, id)
	return err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, user_id, name, target_amount, current_amount, target_date, icon, color, created_at, updated_at FROM goals WHERE id = $1
`

func (q *Queries) GetGoalByID(ctx context.Context, id pgtype.UUID) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoalByID, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.TargetDate,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalsByUserID = `-- name: GetGoalsByUserID :many
SELECT id, user_id, name, target_amount, current_amount, target_date, icon, color, created_at, updated_at FROM goals WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetGoalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, getGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.TargetDate,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $2,
    target_amount = $3,
    current_amount = $4,
    target_date = $5,
    icon = $6,
    color = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, target_amount, current_amount, target_date, icon, color, created_at, updated_at
`

type UpdateGoalParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	TargetAmount  float64     `json:"target_amount"`
	CurrentAmount float64     `json:"current_amount"`
	TargetDate    pgtype.Date `json:"target_date"`
	Icon          string      `json:"icon"`
	Color         string      `json:"color"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.TargetDate,
		arg.Icon,
		arg.Color,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.TargetDate,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
