// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Currency  string             `json:"currency"`
	Balance   float64            `json:"balance"`
	Color     string             `json:"color"`
	Icon      string             `json:"icon"`
	Archived  bool               `json:"archived"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Attachment struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Filename      string             `json:"filename"`
	OriginalName  string             `json:"original_name"`
	MimeType      string             `json:"mime_type"`
	Size          int64              `json:"size"`
	Url           string             `json:"url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Budget struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Amount     float64            `json:"amount"`
	Spent      float64            `json:"spent"`
	Month      int32              `json:"month"`
	Year       int32              `json:"year"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Color     string             `json:"color"`
	Icon      string             `json:"icon"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Debt struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	TotalAmount     float64            `json:"total_amount"`
	RemainingAmount float64            `json:"remaining_amount"`
	InterestRate    float64            `json:"interest_rate"`
	DueDate         pgtype.Date        `json:"due_date"`
	Status          string             `json:"status"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DebtPayment struct {
	ID          pgtype.UUID        `json:"id"`
	DebtID      pgtype.UUID        `json:"debt_id"`
	Amount      float64            `json:"amount"`
	PaymentDate pgtype.Date        `json:"payment_date"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Goal struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Name          string             `json:"name"`
	TargetAmount  float64            `json:"target_amount"`
	CurrentAmount float64            `json:"current_amount"`
	TargetDate    pgtype.Date        `json:"target_date"`
	Icon          string             `json:"icon"`
	Color         string             `json:"color"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Revoked   bool               `json:"revoked"`
}

type Setting struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	ToAccountID pgtype.UUID        `json:"to_account_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Type        string             `json:"type"`
	Amount      float64            `json:"amount"`
	Description string             `json:"description"`
	Notes       pgtype.Text        `json:"notes"`
	Date        pgtype.Date        `json:"date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TransactionTag struct {
	TransactionID pgtype.UUID `json:"transaction_id"`
	TagID         pgtype.UUID `json:"tag_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
