// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	CreateDebtPayment(ctx context.Context, arg CreateDebtPaymentParams) (DebtPayment, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionTag(ctx context.Context, arg CreateTransactionTagParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id pgtype.UUID) error
	DeleteAttachment(ctx context.Context, id pgtype.UUID) error
	DeleteBudget(ctx context.Context, id pgtype.UUID) error
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteDebt(ctx context.Context, id pgtype.UUID) error
	DeleteDebtPayment(ctx context.Context, id pgtype.UUID) error
	DeleteGoal(ctx context.Context, id pgtype.UUID) error
	DeleteSetting(ctx context.Context, arg DeleteSettingParams) error
	DeleteTag(ctx context.Context, id pgtype.UUID) error
	DeleteTransaction(ctx context.Context, id pgtype.UUID) error
	DeleteTransactionTags(ctx context.Context, transactionID pgtype.UUID) error
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]Account, error)
	GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error)
	GetAttachmentsByTransactionID(ctx context.Context, transactionID pgtype.UUID) ([]Attachment, error)
	GetBudgetByID(ctx context.Context, id pgtype.UUID) (Budget, error)
	GetBudgetsByMonthYear(ctx context.Context, arg GetBudgetsByMonthYearParams) ([]Budget, error)
	GetBudgetsByUserID(ctx context.Context, userID pgtype.UUID) ([]Budget, error)
	GetCategoriesByUserID(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetDebtByID(ctx context.Context, id pgtype.UUID) (Debt, error)
	GetDebtPaymentsByDebtID(ctx context.Context, debtID pgtype.UUID) ([]DebtPayment, error)
	GetDebtsByUserID(ctx context.Context, userID pgtype.UUID) ([]Debt, error)
	GetGoalByID(ctx context.Context, id pgtype.UUID) (Goal, error)
	GetGoalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Goal, error)
	GetRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	GetSettingByKey(ctx context.Context, arg GetSettingByKeyParams) (Setting, error)
	GetSettingsByUserID(ctx context.Context, userID pgtype.UUID) ([]Setting, error)
	GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetTagsByUserID(ctx context.Context, userID pgtype.UUID) ([]Tag, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionTags(ctx context.Context, transactionID pgtype.UUID) ([]Tag, error)
	GetTransactionsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error)
	GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]Transaction, error)
	GetTransactionsByType(ctx context.Context, arg GetTransactionsByTypeParams) ([]Transaction, error)
	GetTransactionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserTransactionsSummary(ctx context.Context, arg GetUserTransactionsSummaryParams) (GetUserTransactionsSummaryRow, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
