// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings
WHERE user_id = $1 AND key = $2
`

type DeleteSettingParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Key    string      `json:"key"`
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) error {
	_, err := q.db.Exec(ctx, deleteSetting, arg.UserID, arg.Key)
	return err
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, user_id, key, value, created_at, updated_at FROM settings
WHERE user_id = $1 AND key = $2
`

type GetSettingByKeyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Key    string      `json:"key"`
}

func (q *Queries) GetSettingByKey(ctx context.Context, arg GetSettingByKeyParams) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, arg.UserID, arg.Key)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingsByUserID = `-- name: GetSettingsByUserID :many
SELECT id, user_id, key, value, created_at, updated_at FROM settings
WHERE user_id = $1
`

func (q *Queries) GetSettingsByUserID(ctx context.Context, userID pgtype.UUID) ([]Setting, error) {
	rows, err := q.db.Query(ctx, getSettingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key)
DO UPDATE SET value = $3, updated_at = NOW()
RETURNING id, user_id, key, value, created_at, updated_at
`

type UpsertSettingParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Key    string      `json:"key"`
	Value  string      `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.UserID, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
