// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, account_id, to_account_id, category_id, type, amount, description, notes, date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	ToAccountID pgtype.UUID `json:"to_account_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Type        string      `json:"type"`
	Amount      float64     `json:"amount"`
	Description string      `json:"description"`
	Notes       pgtype.Text `json:"notes"`
	Date        pgtype.Date `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Notes,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Notes,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionTag = `-- name: CreateTransactionTag :exec
INSERT INTO transaction_tags (transaction_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateTransactionTagParams struct {
	TransactionID pgtype.UUID `json:"transaction_id"`
	TagID         pgtype.UUID `json:"tag_id"`
}

func (q *Queries) CreateTransactionTag(ctx context.Context, arg CreateTransactionTagParams) error {
	_, err := q.db.Exec(ctx, createTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const deleteTransactionTags = `-- name: DeleteTransactionTags :exec
DELETE FROM transaction_tags WHERE transaction_id = $1
`

func (q *Queries) DeleteTransactionTags(ctx context.Context, transactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionTags, transactionID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Notes,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionTags = `-- name: GetTransactionTags :many
SELECT t.id, t.user_id, t.name, t.created_at
FROM tags t
JOIN transaction_tags tt ON t.id = tt.tag_id
WHERE tt.transaction_id = $1
`

func (q *Queries) GetTransactionTags(ctx context.Context, transactionID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTransactionTags, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at FROM transactions
WHERE account_id = $1 OR to_account_id = $1
ORDER BY date DESC, created_at DESC
`

func (q *Queries) GetTransactionsByAccountID(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByDateRange = `-- name: GetTransactionsByDateRange :many
SELECT id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at FROM transactions
WHERE user_id = $1 AND date >= $2 AND date <= $3
ORDER BY date DESC, created_at DESC
`

type GetTransactionsByDateRangeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByType = `-- name: GetTransactionsByType :many
SELECT id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at FROM transactions
WHERE user_id = $1 AND type = $2
ORDER BY date DESC, created_at DESC
`

type GetTransactionsByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) GetTransactionsByType(ctx context.Context, arg GetTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at FROM transactions
WHERE user_id = $1
ORDER BY date DESC, created_at DESC
`

func (q *Queries) GetTransactionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactionsSummary = `-- name: GetUserTransactionsSummary :one
SELECT
    COUNT(*)::bigint as total_count,
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::double precision as total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::double precision as total_expense
FROM transactions
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
`

type GetUserTransactionsSummaryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetUserTransactionsSummaryRow struct {
	TotalCount   int64   `json:"total_count"`
	TotalIncome  float64 `json:"total_income"`
	TotalExpense float64 `json:"total_expense"`
}

func (q *Queries) GetUserTransactionsSummary(ctx context.Context, arg GetUserTransactionsSummaryParams) (GetUserTransactionsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserTransactionsSummary, arg.UserID, arg.Date, arg.Date_2)
	var i GetUserTransactionsSummaryRow
	err := row.Scan(&i.TotalCount, &i.TotalIncome, &i.TotalExpense)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = $2,
    to_account_id = $3,
    category_id = $4,
    type = $5,
    amount = $6,
    description = $7,
    notes = $8,
    date = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, account_id, to_account_id, category_id, type, amount, description, notes, date, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID `json:"id"`
	AccountID   pgtype.UUID `json:"account_id"`
	ToAccountID pgtype.UUID `json:"to_account_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Type        string      `json:"type"`
	Amount      float64     `json:"amount"`
	Description string      `json:"description"`
	Notes       pgtype.Text `json:"notes"`
	Date        pgtype.Date `json:"date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Notes,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ToAccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Notes,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
